# Generated by Django 5.2.6 on 2025-09-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_tulio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='imagem',
        ),
    ]
